// The ?puzzle=/&moves=/&solved query-param scheme (see the "Sharing
// links" section in docs/DEVELOPMENT.md) has zero coverage anywhere
// else — every prior check of it was a throwaway script run once by
// hand and discarded. This is the permanent version: a plain puzzle
// link, a partial-progress link round-tripping through a fresh page
// load, a fully-solved link using the terser &solved form, Start Over
// and the puzzle picker both refusing to re-apply a URL's state after
// the initial load, and a couple of malformed &moves values degrading
// to a plain load instead of throwing.
//
// Reads game internals via window.CC (see the "test/debug hooks"
// comment in game.js) rather than bare globals -- game.js is an ES
// module now, so its own top-level scope no longer leaks onto window
// the way a classic <script> did.
import assert from "node:assert/strict";

export const name = "sharing: ?puzzle=/&moves=/&solved links encode and replay correctly";

// Finds one legal (source, target) tap pair from whatever the current
// puzzle happens to be, so this doesn't hardcode term text that could
// go stale if puzzle content changes.
async function makeOneCorrectMove(page) {
  return page.evaluate(() => {
    for (const n of CC.state.nodes) {
      if (CC.isDone(n)) continue;
      for (const gi of n.gs) {
        if (n.connected.includes(gi)) continue;
        const target = CC.state.nodes.find(t => !CC.isBridge(t) && t.gs[0] === gi && t.connected.includes(gi) && t !== n);
        if (target) {
          CC.handleTap(n);
          CC.handleTap(target);
          return true;
        }
      }
    }
    return false;
  });
}

async function shareCurrentPuzzle(page) {
  await page.click("#share-puzzle");
  await page.waitForFunction(() => document.getElementById("share-status").textContent.length > 0);
  return page.evaluate(() => navigator.clipboard.readText());
}

export async function run(page, baseURL) {
  const errors = [];
  page.on("pageerror", e => errors.push(String(e)));
  page.on("console", msg => { if (msg.type() === "error") errors.push(msg.text()); });

  const context = page.context();
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);

  // ---- a fresh, untouched puzzle shares a plain ?puzzle= link ----
  await page.goto(`${baseURL}/index.html`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  const puzzleId = await page.evaluate(() => CC.state.puzzle.id);

  const plainUrl = new URL(await shareCurrentPuzzle(page));
  assert.equal(plainUrl.searchParams.get("puzzle"), puzzleId, "plain share link has the wrong puzzle id");
  assert.equal(plainUrl.searchParams.has("moves"), false, "an untouched puzzle shouldn't share a moves param");
  assert.equal(plainUrl.searchParams.has("solved"), false, "an untouched puzzle shouldn't share a solved flag");

  await page.goto(plainUrl.toString());
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.state.puzzle.id), puzzleId, "plain link didn't select the right puzzle");
  const pickerValue = await page.$eval("#puzzle-picker", el => +el.value);
  const puzzleIndex = await page.evaluate(id => CC.PUZZLES.findIndex(p => p.id === id), puzzleId);
  assert.equal(pickerValue, puzzleIndex, "picker dropdown didn't sync to the puzzle loaded from the link");

  // An unrecognized id degrades to the default puzzle rather than erroring.
  const defaultPuzzleId = await page.evaluate(() => CC.PUZZLES[0].id);
  await page.goto(`${baseURL}/index.html?puzzle=not-a-real-puzzle-id`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.state.puzzle.id), defaultPuzzleId, "unrecognized id should fall back to the default puzzle");

  // ---- a manually-added &mode= overrides the stored preference for
  // this view only, and is never generated by the Share button ----
  await page.evaluate(() => localStorage.setItem("ccMode", "graph"));
  await page.goto(`${baseURL}/index.html?mode=sets`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.mode), "sets", "&mode=sets should override a stored 'graph' preference");
  assert.equal(await page.getAttribute("#mode-sets", "aria-pressed"), "true", "&mode=sets should be reflected on the Sets button");

  await page.goto(`${baseURL}/index.html?mode=star`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.mode), "star", "&mode=star should override a stored 'graph' preference");
  assert.equal(await page.getAttribute("#mode-star", "aria-pressed"), "true", "&mode=star should be reflected on the Star button");

  // Reloading the SAME page without &mode= must revert to the stored
  // preference, proving the override wasn't persisted to localStorage.
  await page.goto(`${baseURL}/index.html`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.mode), "graph", "&mode= must not overwrite the stored preference for later, param-less visits");

  // A garbage &mode= value falls back to the normal stored/default logic.
  await page.goto(`${baseURL}/index.html?mode=bogus`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.mode), "graph", "an invalid &mode= value should fall back to the stored preference, not error");

  const plainShareAfterModeOverride = new URL(await shareCurrentPuzzle(page));
  assert.equal(plainShareAfterModeOverride.searchParams.has("mode"), false, "the Share button must never add &mode= on its own");

  // ---- partial progress shares &moves=, and round-trips exactly ----
  await page.goto(`${baseURL}/index.html`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.ok(await makeOneCorrectMove(page), "couldn't make a first correct move to seed the moves test");
  assert.ok(await makeOneCorrectMove(page), "couldn't make a second correct move to seed the moves test");
  const madeBefore = await page.evaluate(() => CC.state.made);
  const puzzleIdForMoves = await page.evaluate(() => CC.state.puzzle.id);
  const connectedBefore = await page.evaluate(() => CC.state.nodes.filter(n => CC.isDone(n)).map(n => n.word).sort());

  const movesUrl = new URL(await shareCurrentPuzzle(page));
  assert.ok(movesUrl.searchParams.has("moves"), "partial progress should share a moves param");
  assert.equal(movesUrl.searchParams.has("solved"), false, "partial progress shouldn't also set solved");

  await page.goto(movesUrl.toString());
  await page.waitForSelector("#puzzle-title:not(:empty)");
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => CC.state.puzzle.id), puzzleIdForMoves, "moves link loaded the wrong puzzle");
  assert.equal(await page.evaluate(() => CC.state.made), madeBefore, "moves link didn't reconstruct the same progress count");
  const connectedAfter = await page.evaluate(() => CC.state.nodes.filter(n => CC.isDone(n)).map(n => n.word).sort());
  assert.deepEqual(connectedAfter, connectedBefore, "moves link reconstructed a different set of connections");

  // Start Over must not re-apply the URL's moves on a later loadPuzzle call.
  await page.click("#reset");
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => CC.state.made), 0, "Start Over should not re-replay a shared moves param");

  // Switching puzzles via the picker must not leak stale moves either.
  await page.goto(movesUrl.toString());
  await page.waitForSelector("#puzzle-title:not(:empty)");
  await page.waitForTimeout(150);
  const otherIndex = (puzzleIndex + 1) % (await page.evaluate(() => CC.PUZZLES.length));
  // By option *value* (each real option's value is its PUZZLES index --
  // see the picker-population comment in game.js), not DOM position: the
  // picker now has a disabled placeholder option at position 0, so a
  // raw positional { index: otherIndex } would silently select one
  // puzzle too early instead of erroring.
  await page.selectOption("#puzzle-picker", { value: String(otherIndex) });
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => CC.state.made), 0, "switching puzzles via the picker should not carry over a shared moves param");

  // ---- a fully-solved puzzle shares the terser &solved flag instead ----
  await page.goto(`${baseURL}/index.html`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  await page.click("#show-solution");
  await page.waitForTimeout(150);
  const need = await page.evaluate(() => CC.state.need);
  assert.equal(await page.evaluate(() => CC.state.made), need, "Show Solution should have fully completed the puzzle before sharing it");

  const solvedUrl = new URL(await shareCurrentPuzzle(page));
  assert.equal(solvedUrl.searchParams.has("solved"), true, "a fully-solved puzzle should share &solved");
  assert.equal(solvedUrl.searchParams.has("moves"), false, "a fully-solved puzzle shouldn't also share &moves");

  await page.goto(solvedUrl.toString());
  await page.waitForSelector("#puzzle-title:not(:empty)");
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => CC.state.made), await page.evaluate(() => CC.state.need), "&solved link didn't fully complete the puzzle");

  // A bare &solved (no value at all) must work too -- that's the form
  // documented as "shorthand", not just ...&solved=1.
  await page.goto(`${baseURL}/index.html?puzzle=${encodeURIComponent(puzzleId)}&solved`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => CC.state.made), await page.evaluate(() => CC.state.need), "bare &solved flag (no value) should still fully complete the puzzle");

  // ---- malformed &moves degrades to a plain load, never throws ----
  for (const badMoves of ["!!!not-valid!!!", "A"]) {
    await page.goto(`${baseURL}/index.html?puzzle=${encodeURIComponent(puzzleId)}&moves=${encodeURIComponent(badMoves)}`);
    await page.waitForSelector("#puzzle-title:not(:empty)");
    assert.equal(await page.evaluate(() => CC.state.puzzle.id), puzzleId, `corrupted moves param "${badMoves}" should still load the puzzle`);
  }

  // ---- ?category= shows the overview screen instead of a single
  // puzzle -- listing every puzzle in that category, not auto-entering
  // any of them (see the design note above showOverview in game.js) ----
  const someCategory = await page.evaluate(() => CC.PUZZLES[0].category);
  const expectedInCategory = await page.evaluate(
    cat => CC.PUZZLES.filter(p => p.category === cat).map(p => p.title).sort(),
    someCategory
  );
  await page.goto(`${baseURL}/index.html?category=${encodeURIComponent(someCategory)}`);
  await page.waitForSelector("#overview-title");
  assert.equal(await page.textContent("#overview-title"), someCategory, "overview title should be the shared category");
  assert.equal(await page.locator("#puzzle-overview").isVisible(), true, "overview should be visible for ?category=");
  assert.equal(await page.locator("#puzzle-view").isVisible(), false, "puzzle-view should be hidden while the overview is showing");
  const cardTitles = await page.evaluate(() =>
    Array.from(document.querySelectorAll("#overview-list .related-card strong")).map(el => el.textContent).sort()
  );
  assert.deepEqual(cardTitles, expectedInCategory, "overview should list exactly the puzzles in that category");

  // Picking a card enters that puzzle directly and hides the overview.
  await page.locator("#overview-list .related-card").first().click();
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.state.puzzle.category), someCategory, "clicking an overview card loaded the wrong puzzle");
  assert.equal(await page.locator("#puzzle-overview").isVisible(), false, "overview should hide once a puzzle is entered");
  assert.equal(await page.locator("#puzzle-view").isVisible(), true, "puzzle-view should show once a puzzle is entered");

  // An unrecognized category degrades to the default puzzle, same
  // "stale link still just opens the game" philosophy as ?puzzle=.
  await page.goto(`${baseURL}/index.html?category=NoSuchCategoryAtAll`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.state.puzzle.id), defaultPuzzleId, "unrecognized category should fall back to the default puzzle");
  assert.equal(await page.locator("#puzzle-overview").isVisible(), false, "overview should not show for an unrecognized category");

  // ---- &puzzles=id1,id2 shows the overview for exactly those puzzles,
  // in the order given, silently dropping any unrecognized id ----
  const puzzleA = await page.evaluate(() => CC.PUZZLES[0].id);
  const puzzleB = await page.evaluate(() => CC.PUZZLES[1].id);
  await page.goto(`${baseURL}/index.html?puzzles=${puzzleA},not-a-real-id,${puzzleB}`);
  await page.waitForSelector("#overview-title");
  const multiTitles = await page.evaluate(() =>
    Array.from(document.querySelectorAll("#overview-list .related-card strong")).map(el => el.textContent)
  );
  assert.deepEqual(
    multiTitles,
    await page.evaluate(([a, b]) => [CC.PUZZLES.find(p => p.id === a).title, CC.PUZZLES.find(p => p.id === b).title], [puzzleA, puzzleB]),
    "&puzzles= should list exactly the recognized ids, in order, dropping the unrecognized one"
  );

  // All-unrecognized ids degrades to the default puzzle, not an empty
  // or broken overview.
  await page.goto(`${baseURL}/index.html?puzzles=nope-1,nope-2`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  assert.equal(await page.evaluate(() => CC.state.puzzle.id), defaultPuzzleId, "an all-unrecognized &puzzles= list should fall back to the default puzzle");

  // ---- the overview's own Share button reproduces the same view ----
  await page.goto(`${baseURL}/index.html?puzzles=${puzzleA},${puzzleB}`);
  await page.waitForSelector("#overview-title");
  await page.click("#overview-share-btn");
  await page.waitForFunction(() => document.getElementById("overview-share-status").textContent.length > 0);
  const overviewShareUrl = new URL(await page.evaluate(() => navigator.clipboard.readText()));
  assert.deepEqual(
    overviewShareUrl.searchParams.get("puzzles").split(","),
    [puzzleA, puzzleB],
    "the overview's Share button should encode exactly the puzzles it's showing"
  );

  // ---- "Browse: <category>" reopens the overview for the current
  // puzzle's category, and the picker still works as a bypass while the
  // overview is showing (selecting a puzzle enters it directly) ----
  await page.goto(`${baseURL}/index.html?puzzle=${encodeURIComponent(puzzleId)}`);
  await page.waitForSelector("#puzzle-title:not(:empty)");
  const puzzleCategory = await page.evaluate(() => CC.state.puzzle.category);
  await page.click("#browse-category");
  await page.waitForSelector("#overview-title");
  assert.equal(await page.textContent("#overview-title"), puzzleCategory, "Browse should open the current puzzle's own category");

  await page.selectOption("#puzzle-picker", { value: String(puzzleIndex) });
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => CC.state.puzzle.id), puzzleId, "the picker should still work as a direct bypass while the overview is showing");
  assert.equal(await page.locator("#puzzle-overview").isVisible(), false, "selecting from the picker should close the overview");

  // ---- finishing a puzzle solved via Show Solution offers to share its
  // related set when it has one (reuses the completion-screen section
  // covered more directly in the completion-screen's own feature, this
  // just confirms the share link it produces actually round-trips) ----
  const relatedPuzzleId = await page.evaluate(() => {
    const p = CC.PUZZLES.find(x => x.relatedPuzzles && x.relatedPuzzles.length);
    return p ? p.id : null;
  });
  if (relatedPuzzleId) {
    await page.goto(`${baseURL}/index.html?puzzle=${encodeURIComponent(relatedPuzzleId)}`);
    await page.waitForSelector("#puzzle-title:not(:empty)");
    await page.click("#show-solution");
    await page.waitForTimeout(150);
    await page.click(".related-share-link");
    await page.waitForFunction(() => document.querySelector(".related-share-link + [role=status]")?.textContent.length > 0);
    const relatedShareUrl = new URL(await page.evaluate(() => navigator.clipboard.readText()));
    const sharedIds = relatedShareUrl.searchParams.get("puzzles").split(",");
    assert.ok(sharedIds.includes(relatedPuzzleId), "sharing related puzzles should include the just-finished puzzle itself");
    assert.ok(sharedIds.length > 1, "sharing related puzzles should include at least one related puzzle too");
  }

  assert.equal(errors.length, 0, `console errors:\n${errors.join("\n")}`);
}
