// Optional, hand-authored final layouts for Star mode.
// Generated by tools/import-star-layout.mjs; do not edit by hand.
import layout0 from "./models-of-the-divided-mind.js";

export const STAR_LAYOUTS = {
  [layout0.puzzleId]: layout0
};

export default STAR_LAYOUTS;
